syria_master_Airbase_name_table = {
 "Abu al-Duhur",
 "Adana Sakirpasa",
 "Al Qusayr",
 "An Nasiriyah",
 "Beirut-Rafic Hariri", 
 "Damascus", 
 "Marj as Sultan South", 
 "Al-Dumayr",
 "Eyn Shemer",
 "Haifa",
 "Hama",
 "Hatay",
 "Incirlik",
 "Jirah",
 "Khalkhalah",
 "King Hussein Air College",
 "Kiryat Shmona",
 "Bassel Al-Assad",
 "Marj as Sultan North",
 "Marj Ruhayyil",
 "Megiddo",
 "Mezzeh",
 "Minakh",
 "Aleppo",
 "Palmyra",
 "Qabr as Sitt",
 "Ramat David",
 "Kuweires",
 "Rayak",
 "Rene Mouawad",
 "Tabqa",
 "Taftanaz",
 "Wujah Al Hajar"
}